worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Load Balancing
    upstream seckill_backend {
        # Round Robin (default)
        server seckill-app-1:8080 weight=1;
        server seckill-app-2:8080 weight=1;
        
        # Least Connections (uncomment to user)
        # least_conn;
        
        # IP Hash (uncomment to use)
        # ip_hash;
    }

    server {
        listen       80;
        server_name  localhost;

        # Static Separation
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # Api Proxy
        location /api/ {
            proxy_pass http://seckill_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Remove /api prefix when forwarding to backend if needed
            # rewrite ^/api/(.*)$ /$1 break; 
            # In our case, backend controllers are mapped directly likely without /api prefix
            # The JS uses /api/product/detail/1 -> Needs to go to /product/detail/1 on backend
            rewrite ^/api/(.*) /$1 break;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
